[package]
name = "ratatui-starter"
version = "0.1.0"
edition = "2024"
license = "MIT"
rust-version = "1.98"
description = "A minimal ratatui starter template for tui"
repository = "https://github.com/mancuoj/ratatui-starter"
homepage = "https://github.com/mancuoj/ratatui-starter"
readme = "README.md"
keywords = ["ratatui", "tui", "starter", "terminal", "cli"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
anyhow = "1"
crossterm = "0.29.0"
ratatui = "0.30.2"

[profile.release]
lto = "thin"
strip = true
